name: Build and Deploy 

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: |
          dotnet restore

      - name: List .csproj files
        run: |
          for /r /d %%i in (*.csproj) do (
            echo %%i
          )
        shell: powershell
        env:
          DOTNET_ROOT: C:\Users\runneradmin\AppData\Local\Microsoft\dotnet

      - name: Build and Publish
        run: |
          for /r /d %%i in (*.csproj) do (
            dotnet build --configuration Release "%%i"
            dotnet publish -c Release -o ./publish "%%i"
          )
        shell: powershell
        env:
          DOTNET_ROOT: C:\Users\runneradmin\AppData\Local\Microsoft\dotnet
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: dotnet-app
          path: ./publish
