name: Build and Deploy 

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies and build projects
        run: |
          dotnet restore ""
          dotnet build --configuration Release "**/*.csproj"
          dotnet publish -c Release -o ./publish/**/*.csproj"
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: dotnet-app
          path: Artifact
          
